cardno_len: 16
cardno_len_min: 13
cardsec_len: 4
cardsec_len_min: 2
cardtype: 'VISA,JCB,AmericanExpress,MASTER,DinersClub'
cardlimit_mon: '01,02,03,04,05,06,07,08,09,11,12'
cardlimit_year: '2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026,2027,2028'
kintoneapi_url: 'https://ac-system.cybozu.com/k/v1/record.json'
kintoneapi_id: 'system_api'
kintoneapi_pw: 's63mxAm$'
kintoneapi_appid: 424
webregist_url: hogehoge
webregist_awskey: secretkey
webregist_awspw: hogehogekey

productclassex_sim_payment: '9,10'
productclassex_sp_payment: '10,12'
producttype_ex_sim_type: 2
producttype_ex_sp_type: 1
productclass_payonce_type: 10

#  simの注記表示対象外　UQmobile

shoppingex_exclude_sim_maker: '13'

# 重要事項の表示対象メーカ

shoppingex_important_matter_disp_maker: '14'

category_sumaho_id: 2
category_sim_id: 1

shoppingex_delivery_fix_fee: 500
fdroute_reservedparams:　'page_no,category_id,tag_id'
stext_len: 300


# ============= 拡張項目のID =============
product_ex_img_01: 			1
product_ex_img_02: 			2
product_ex_img_03: 			8
product_ex_infotitle_01: 		38
product_ex_infotitle_02: 		39
product_ex_infotitle_03: 		40
product_ex_info_01: 		9
product_ex_info_02: 		10
product_ex_info_03: 		11
product_ex_sim_size: 		4
product_ex_carrier: 		41
product_ex_sale_date: 		16
product_ex_msg: 			6
product_ex_p_os: 				12
product_ex_p_body_size: 		14
product_ex_p_weight: 			15
product_ex_p_screen_size: 	17
product_ex_p_screen_reso: 	18
product_ex_p_main_cam: 		19
product_ex_p_sub_cam: 		20
product_ex_p_battery: 		21
product_ex_p_cpu: 			22
product_ex_p_rom: 			23
product_ex_p_ram: 			24
product_ex_p_etc_waterproof: 	25
product_ex_p_etc_tethering: 	26
product_ex_p_etc_wifi: 		27
product_ex_p_etc_bluetooth: 	28
product_ex_p_etc_gps: 		29
product_ex_p_etc_infrared: 	30
product_ex_p_etc_pay: 		31
product_ex_s_init_price: 		32
product_ex_s_speed: 			33
product_ex_s_data: 			34
product_ex_s_speed_up: 		35
product_ex_s_speed_down: 		36
product_ex_s_etc_sms: 		42
product_ex_s_etc_voice: 		43
# ============= /拡張項目のID =====
