http_cache:
    enabled: true
    age: 10
    # フロントでキャッシュを適用させる画面のrouteを設定
    route:
        - homepage
        - product_list
        - product_detail
#        - block_category
#        - block_news
#        - block_search_product
#        - help_about
        - help_guide
        - help_privacy
        - help_tradelaw
#        - help_agreement
