<?php
namespace Plugin\ProductClassEx\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductClassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductClassExRepository extends EntityRepository
{
}
