<?php
/*
 * Copyright(c) 2015 SystemFriend Inc. All rights reserved.
 * http://ec-cube.systemfriend.co.jp/
 */

namespace Plugin\ExcludeProductPayment\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CprProductRedirectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExcludeProductPaymentRepository extends EntityRepository
{
}
